export const FETCH_POPULAR = 'FETCH_POPULAR';
export const FETCH_UPCOMING = 'FETCH_UPCOMING';
export const FETCH_TOP_RATED = 'FETCH_TOP_RATED';
export const FETCH_KIDS_POPULAR = 'FETCH_KIDS_POPULAR';
export const FETCH_NOW_PLAYING = 'FETCH_NOW_PLAYING';
export const FETCH_SEARCH = 'FETCH_SEARCH';
//TvShows types
export const FETCH_TV_POPULAR = 'FETCH_TV_POPULAR'
export const FETCH_TV_TOP_RATED = 'FETCH_TV_TOP_RATED'
export const FETCH_TV_ON_THE_AIR = 'FETCH_TV_ON_THE_AIR'
export const FETCH_TV_AIRING_TODAY = 'FETCH_TV_AIRING_TODAY'
export const FETCH_TV_SEARCH = 'FETCH_TV_SEARCH'
